language: python
addons:
    artifacts:
        s3_region: "us-west-2"
        paths:
            - screenshots/
    apt:
        packages:
            - libpng-dev
            - zlib1g-dev
            - libxtst-dev
            - libtesseract-dev
            - libopencv-dev
            - socat
            - wmctrl
cache:
    pip: true
python:
    - '2.7'
    - '3.4'
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - bash tests/init_environment.sh
script:
    - pytest tests/
